FROM python:slim-bullseye

LABEL version="1.0" 
LABEL description="base image = python, add install aws cli"  

# pythonスクリプトの配備
COPY resource /tmp/

# aws cliのインストール

# 前提パッケージのインストール
RUN apt-get update && apt-get install -y curl unzip sudo \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && apt-get clean all && rm -rf /var/lib/apt/lists/*\
    && unzip awscliv2.zip && rm awscliv2.zip\
    && sudo ./aws/install && rm -r ./aws \
    && pip install --no-cache-dir -r /tmp/requirements.txt

# CMD [ "python", "/tmp/resource/src/main.py" ]
